title: Sterling
author: Tristan Dyer
email: atristandyer@gmail.com
descriptions: >-
  A web-based visualizer for relational modeling languages
github_username: sterling-js
sass:
  sass_dir: _sass
plugins:
  - jekyll-octicons
